version: '3.4'

volumes:
    mysql-data:
        driver: "local"
networks: 
    localnet:
        driver: bridge

services:
    apache:
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: apache
        ports:
            - 8000:80
        volumes: 
            - ./src:/var/www/html/        
        user: www-data
        networks: 
            - localnet
        depends_on: 
            - mysql
    mysql:
        image: mysql:5.7
        container_name: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes: 
            - mysql-data:/var/lib/mysql:rw
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: test
            MYSQL_USER: dev
            MYSQL_PASSWORD: 123456
        networks: 
            - localnet
        ports:
            - 3307:3306
    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1
        networks: 
            - localnet